const testList = [
	{'id':'gFaWRKc_PcWEhHcOeDPqj','src':'https://upload.wikimedia.org/wikipedia/commons/5/54/Vincent_Van_Gogh_-_Wheatfield_With_Cornflowers_-_Google_Art_Project.jpg','title':'Wheat Field with Cornflowers','artist':'Vincent van Gogh','artistLink':'/wiki/Vincent_van_Gogh','titleLink':'','provider':'Wikipedia','providerLink':'https://wikipedia.org'},
	{'id':'Bb6jfEK4ZNVHpiIYMsEiq','src':'https://upload.wikimedia.org/wikipedia/commons/d/d2/Hans_Holbein%2C_the_Younger_-_Sir_Thomas_More_-_Google_Art_Project.jpg','title':'Portrait of Sir Thomas More','artist':'Hans Holbein the Younger','artistLink':'/wiki/Hans_Holbein_the_Younger','titleLink':'https://wikipedia.org/wiki/Portrait_of_Sir_Thomas_More_(Holbein)','provider':'Wikipedia','providerLink':'https://wikipedia.org'},
	{'id':'-xy6N6vZITmtfQ5UVqwMm','src':'https://upload.wikimedia.org/wikipedia/commons/8/87/Valentin_de_Boulogne_-_Soldiers_Playing_Cards_and_Dice_%28The_Cheats%29.jpg','title':'Soldiers Playing Cards and Dice (The Cheats)','artist':'Valentin de Boulogne','artistLink':'/wiki/Valentin_de_Boulogne','titleLink':'','provider':'Wikipedia','providerLink':'https://wikipedia.org'},
	{'id':'WU2wbWzeRRO-lujWxkO7D','src':'https://upload.wikimedia.org/wikipedia/commons/6/61/Thomas_Cole_-_The_Ages_of_Life_-_Youth_-_WGA05140.jpg','title':'The Voyage of Life: Youth','artist':'Thomas Cole','artistLink':'/wiki/Thomas_Cole','titleLink':'https://wikipedia.org/wiki/The_Voyage_of_Life','provider':'Wikipedia','providerLink':'https://wikipedia.org'},
	{'id':'xLQspUEmy1UkuvvtpT_Uw','src':'https://lh3.googleusercontent.com/Bawo7r1nPZV6sJ4OHZJHdKV_4Ky59vquAR7KoUXcNZgx9fqTaOW-QaOM9qoyYhOTAopzjt9OIfW06RMwa-9eJW9KjQw=s0','title':'The Singel Bridge at the Paleisstraat in Amsterdam','artist':'George Hendrik Breitner','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-A-3580','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'lyWVH9j05TE3bvb5k7R3o','src':'https://upload.wikimedia.org/wikipedia/commons/2/20/Albrecht_D%C3%BCrer_-_Portrait_of_D%C3%BCrer%27s_Father_at_70.jpg','title':'Portrait of Dürer\'s Father at 70','artist':'Albrecht Dürer','artistLink':'/wiki/Albrecht_D%C3%BCrer','titleLink':'https://wikipedia.org/wiki/Portrait_of_D%C3%BCrer%27s_Father_at_70','provider':'Wikipedia','providerLink':'https://wikipedia.org'},
	{'id':'Zqa1aDnemyV9LCxc4KXfk','src':'https://lh3.googleusercontent.com/gShVRyvLLbwVB8jeIPghCXgr96wxTHaM4zqfmxIWRsUpMhMn38PwuUU13o1mXQzLMt5HFqX761u8Tgo4L_JG1XLATvw=s0','title':'The Sampling Officials of the Amsterdam Drapers’ Guild, Known as ‘The Syndics’','artist':'Rembrandt van Rijn','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-C-6','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'2rwxyeq-vEJA4t9mqF4i9','src':'https://lh3.googleusercontent.com/KA2hIo0BlMDmyQDEC3ixvp9WHgcyJnlAvWtVcZmExh9ocPoZdQGRJh7bZjE2Mx2OGC0Zi3QGHGP0LlmuFgRlIYs36Sgn5G2OD-0MaTo=s0','title':'Italian Landscape with a Draughtsman','artist':'Jan Both','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-C-109','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'iuBOwV7cF2X3icstrdYIS','src':'https://lh3.googleusercontent.com/oQm3RtsPba1sjclncD_IdJmy5InOcklLLjja5URXQb5K08ZMU_jBQKp3aPiHcFeGLLbnI8YqYWHT02cbJp5xCVDjTTN1rMjxeGET6q3Z=s0','title':'View of Houses in Delft, Known as ‘The Little Street’','artist':'Johannes Vermeer','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-A-2860','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'wdKwZTkmbjWH0GHc3m5Bo','src':'https://lh3.googleusercontent.com/7qzT0pbclLB7y3fdS1GxzMnV7m3gD3gWnhlquhFaJSn6gNOvMmTUAX3wVlTzhMXIs8kM9IH8AsjHNVTs8em3XQI6uMY=s0','title':'Self-portrait','artist':'Rembrandt van Rijn','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-A-4691','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'rHVqMTGT3DxI5WBJB2zKR','src':'https://lh3.googleusercontent.com/bMCQgUbifzAl-How19Ru06KYgdVuND2pdYzY81zIx3MJ0ld6yqzPnWLVUOu0Aj1JNgK-lFDT2CSjfmQ-erpBdJ6AM4XGAwuQoivxWpJ8=s0','title':'A Militiaman Holding a Berkemeyer, Known as the ‘Merry Drinker’','artist':'Frans Hals','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-A-135','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'NcnRwBBzZBJ6JcMfAkypE','src':'https://lh3.googleusercontent.com/moxL3z7zz5j_5gQCgvRGcmLD-RDhVgZvA2NGREYgkLTkYUbGa4Ts-57UaQ4ilN38xWX6w_gb_eU6hkMZcC-wfMg5NQ=s0','title':'Mary Magdalene','artist':'Jan van Scorel','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-A-372','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'vsR-NL6c_lzw-2zDKAISd','src':'https://lh3.googleusercontent.com/3EDrQy1jW6akN2k8eAeCECHJ1FmvM1f2pb9a-de51ErcQcghh7cbpzFIh-QYdcGfpi3FjxH1AP6C_FvPNR-I9n8I4No=s0','title':'The Windmill at Wijk bij Duurstede','artist':'Jacob Isaacksz van Ruisdael','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-C-211','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'he0NP8l5ZZiHiPoPL7MmY','src':'https://upload.wikimedia.org/wikipedia/commons/7/71/The_Annunciation%2C_with_Saint_Emidius_-_Carlo_Crivelli_-_National_Gallery.jpg','title':'The Annunciation, with Saint Emidius','artist':'Carlo Crivelli','artistLink':'/wiki/Carlo_Crivelli','titleLink':'https://wikipedia.org/wiki/The_Annunciation,_with_Saint_Emidius','provider':'Wikipedia','providerLink':'https://wikipedia.org'},
	{'id':'QW9X_USFZ5OXdedCN3PGY','src':'https://lh3.googleusercontent.com/nAGClUPzsX6AlHMMhWo0Wa3vEN7OlG6T4TmdlsHzeZigky3Gv6_TLhF4GakOfGYtW_GCHBQOwc92hpmaS_MrtK4FTeRYOnpib05HnvQENA=s0','title':'Floral Still Life','artist':'Hans Bollongier','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-A-799','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'leoDW21a1ouM1FhvnZCYA','src':'https://upload.wikimedia.org/wikipedia/commons/d/d4/Pierre-Auguste_Renoir%2C_French_-_The_Large_Bathers_-_Google_Art_Project.jpg','title':'Les Grandes Baigneuses','artist':'Pierre-Auguste Renoir','artistLink':'/wiki/Pierre-Auguste_Renoir','titleLink':'https://wikipedia.org/wiki/Les_Grandes_Baigneuses_(Renoir)','provider':'Wikipedia','providerLink':'https://wikipedia.org'},
	{'id':'kHE_7dcngM_8CJIGPM9kf','src':'https://lh3.googleusercontent.com/BMvxPb9RF9F-qz68PAIIrROTp7G352oNEzZWmmT-H1YXSgf2Id33oQBssFYnPL52KwiyFgYY1pSInpEVrhrx1OViFQ=s0','title':'Children of the Sea','artist':'Jozef Israëls','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-A-2382','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'3WQGIPlgiHbmLTknMT-ex','src':'https://lh3.googleusercontent.com/zjehg1KWc2C2s4c3ThD3v1ROk8PFjj2c-6ZcIoLzmBp-bQ17AkF7EijTqWuXx6YbGWrAJA04Tqm3AVcLsqEifHEyMAbEoZ9ROiUUZjbYNw=s0','title':'The Fête champêtre','artist':'Dirck Hals','provider':'Rijksmuseum','titleLink':'http://www.rijksmuseum.nl/en/collection/SK-A-1796','providerLink':'https://www.rijksmuseum.nl/en'},
	{'id':'AOCMq2Dpu9gN0hljSIDze','src':'https://upload.wikimedia.org/wikipedia/commons/5/50/John_Martin_-_The_Great_Day_of_His_Wrath_-_Google_Art_Project.jpg','title':'The Great Day of His Wrath','artist':'John Martin','artistLink':'/wiki/John_Martin_(painter)','titleLink':'https://wikipedia.org/wiki/The_Great_Day_of_His_Wrath','provider':'Wikipedia','providerLink':'https://wikipedia.org'},
	{'id':'WWxWWPZij1-QBlr1LkOJP','src':'https://upload.wikimedia.org/wikipedia/commons/7/7e/Pieter_Brueghel_the_Elder_-_The_Dutch_Proverbs_-_Google_Art_Project.jpg','title':'Netherlandish Proverbs','artist':'Pieter Bruegel the Elder','artistLink':'/wiki/Pieter_Bruegel_the_Elder','titleLink':'https://wikipedia.org/wiki/Netherlandish_Proverbs','provider':'Wikipedia','providerLink':'https://wikipedia.org'},
]

export default testList
